version: '3.1'
services:

  postgres:
    container_name: pg-container
    image: postgres
    env_file:
      - database.env
    ports:
      - "5432:5432"

  redis:
    container_name: redis-container
    image: "redis:alpine"
    ports:
      - "6379:6379"

  adminer:
    container_name: adminer-container
    image: adminer:4.8.1
    ports:
      - 8181:8080
